exchange:
  api:
    liveUrl: ${EXCHANGE_API_LIVE_URL}
    accessKey: ${EXCHANGE_API_ACCESS_KEY}

spring:
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=50000,expireAfterAccess=60000s
